apiVersion: apps/v1
kind: Deployment
metadata:
  name:     
  labels:
    app: ipfs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      containers:
      - name: ipfs
        image: vkrishna47/ipfs-docker:v2.0
